[project]
name = "wimsey"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Ben", email = "unknown@domain.invalid" }
]
dependencies = [
    'ibis-framework[all]',
    "ufo-tools>=0.3.0",
]
readme = "README.md"
requires-python = ">= 3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "ipdb>=0.13.13",
    "ipython>=8.21.0",
]

[tool.hatch.metadata]
allow-direct-references = true
