[project]
site_name = "Wimsey"
site_dir = "wimsey-docs"
site_description = "Lightweight, flexible data contracts with Wimsey"
site_author = "Ben Rutter"
site_url = "https://benrutter.codeberg.page/wimsey-site"
repo_url = "https://codeberg.org/benrutter/wimsey"
repo_name = "benrutter/wimsey"
extra_css = ["stylesheets/extra.css"]
extra_javascript = ["javascript/dither.js"]
nav = [
  "index.md",
  "quick-start.md",
  "test-catalogue.md",
  "api.md",
]

[project.theme]
language = "en"
features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "header.autohide",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.path",
    "navigation.sections",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
]

[project.theme.icon]
logo = "lucide/search"
repo = "simple/codeberg"

[project.theme.font]
text = "Funnel Display"
code = "Space Mono"

[[project.theme.palette]]
scheme = "slate"
primary = "orange"
accent = "orange"

[[project.extra.social]]
icon = "simple/codeberg"
link = "https://codeberg.org/benrutter/wimsey"

[[project.extra.social]]
icon = "simple/github"
link = "https://github.com/benrutter/wimsey"

[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.toc]
permalink = true
[project.markdown_extensions.pymdownx.arithmatex]
generic = true
[project.markdown_extensions.pymdownx.betterem]
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.emoji]
emoji_generator = "zensical.extensions.emoji.to_svg"
emoji_index = "zensical.extensions.emoji.twemoji"
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.magiclink]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.smartsymbols]
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
combine_header_slug = true
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true
[project.markdown_extensions.pymdownx.tilde]
[project.markdown_extensions.pymdownx.tabbed.slugify]
object = "pymdownx.slugs.slugify"
kwds = { case = "lower" }

[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]
paths = ["src"]

[project.plugins.mkdocstrings.handlers.python.options]
inherited_members = true
show_source = true
show_signature = true
show_signature_annotations = true
separate_signature = true
signature_crossrefs = true
