when:
  - event: pull_request
    branch: main

steps:
  - name: tests
    image: python
    commands:
      - python -m pip install pipx
      - pipx install uv
      - uv run coverage run -m pytest
      - uv run coverage report --fail-under=100
      - uv run ty check wimsey
