when:
  - event: pull_request
    branch: main

steps:
  - name: tests
    image: python
    commands:
      - python -m pip install --upgrade pip
      - python -m pip install -r requirements-dev.lock
      - python -m coverage run -m pytest
      - python -m coverage report --fail-under=100
      - python -m ty check wimsey
