name: Deploy
on: workflow_dispatch

jobs:
  build:
    name: Deploy docs to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Build and Deploy
        run: |
          pip install --upgrade pip
          pip install -r requirements-dev.lock
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git config pull.rebase false
          git pull origin main --allow-unrelated-histories
          git pull origin gh-pages --allow-unrelated-histories
          python -m mkdocs gh-deploy
